normalize_state: True
locoman:
  tokenizer:
    hidden_dim: 128 # TODO: this needs to be the same as modality.output_dim.
    nhead: 4
    dim_head: 32
    dropout: 0.1
    main_image:
      output_dim: 128 # this needs to be the same as tokenizer.hidden_dim
      weights: DEFAULT
      resnet_model: resnet18
      num_of_copy: 1
      token_num: 16
    wrist_image:
      output_dim: 128
      weights: DEFAULT
      resnet_model: resnet18
      num_of_copy: 1
      token_num: 8
    body_pose_state:
      input_dim: 6
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    eef_pose_state:
      input_dim: 12
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    eef_to_body_pose_state:
      input_dim: 12
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    gripper_state:
      input_dim: 2
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
  action_head:
    eef_pose:
      type: transformer
      input_dim: 128
      output_dim: 12
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
    body_pose:
      type: transformer
      input_dim: 128
      output_dim: 6
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
    gripper:
      type: transformer
      input_dim: 128
      output_dim: 2
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
human:
  tokenizer:
    hidden_dim: 128
    nhead: 4
    dim_head: 32
    dropout: 0.1
    main_image:
      output_dim: 128 
      weights: DEFAULT
      resnet_model: resnet18
      num_of_copy: 1
      token_num: 16
    # wrist_image:
    #   output_dim: 128
    #   weights: DEFAULT
    #   resnet_model: resnet18
    #   num_of_copy: 1
    #   token_num: 8
    body_pose_state:
      input_dim: 6
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    eef_pose_state:
      input_dim: 12
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    eef_to_body_pose_state:
      input_dim: 12
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
    gripper_state:
      input_dim: 2
      output_dim: 128
      widths: [128, 128]
      tanh_end: False
      ln: True
      token_num: 4
  action_head:
    eef_pose:
      type: transformer
      input_dim: 128
      output_dim: 12
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
    body_pose:
      type: transformer
      input_dim: 128
      output_dim: 6
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
    gripper:
      type: transformer
      input_dim: 128
      output_dim: 2
      crossattn_modality_dropout: 0.1
      crossattn_heads: 4
      crossattn_dim_head: 16
      action_horizon: 60
