output_len:
  eef_pose: 6
  body_pose: 6
  gripper: 6
trunk_mode: encoder_decoder
hidden_dim: 128
dropout: 0.4
nheads: 16
dim_feedforward: 256
enc_layers: 4
dec_layers: 4
pre_norm: False
token_postprocessing: none